version: "3"

services:
  # database
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 9EY449gpWPR7aGc7
    ports:
      - '33306:3306'
    volumes:
      - ./mysql:/etc/mysql/mysql.conf.d
      - ./sql:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 9EY449gpWPR7aGc7
    links:
      - mysql:mysql
    ports:
      - 38000:80

  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass ingirls
    ports:
      - '36379:6379'
    volumes:
      - ./data/redis:/data

  # consul
  consul:
    image: consul:latest
    container_name: consul
    environment: 
      CONSUL_HTTP_ADDR: 127.0.0.1:8500
    command: consul agent -config-file=/consul/config
    ports:
      - '38500:8500'
    volumes:
      - ./consul:/consul/config
      - ./data/consul:/consul/data

  # loki
  loki:
    image: grafana/loki
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./log/grafana:/var/log
    ports:
      - "33100:3100"
  
  # promtail
  promtail:
    image: grafana/promtail
    container_name: promtail
    volumes:
      - /data/logs:/var/log
      - ./log/promtail/tmp:/tmp
      - ./promtail/config:/etc/promtail
    command: -config.file=/etc/promtail/docker-config.yaml
    ports:
      - "39080:9080"

  # prometheus
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./data/prometheus:/prometheus/data
      - ./log/prometheus:/var/log
      - ./prometheus:/etc/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "39090:9090"
      
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
      - ./log/prometheus:/var/log
    command: --config.file=/etc/alertmanager/alertmanager.yml
    ports:
      - "39093:9093"
     
  # grafana
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "33000:3000"

  # gateway
  gateway-api:
    build: ./go14
    container_name: gateway-api
    command: bash -c "syslogd && make run"
    environment: 
      CONSUL_ADDR: consul:8500
    volumes:
      - ../gateway:/go/src/myapp
    ports:
      - "38080:8080"


  # srv & api
  user-srv:
    build: ./go14
    container_name: user-srv
    command: bash -c "syslogd && make srv"
    environment: 
      CONSUL_ADDR: consul:8500
      PROMETHEUS_ADDR: user-srv:8088
    depends_on:
      - consul
    volumes:
      - ../user:/go/src/myapp
      - /data/logs:/go/src/myapp/logs

  user-api:
    container_name: user-api
    build: ./go14
    command: bash -c "syslogd && make api"
    environment: 
      CONSUL_ADDR: consul:8500
      PROMETHEUS_ADDR: user-api:8088
    depends_on:
      - user-srv
    volumes:
      - ../user:/go/src/myapp
      - /data/logs:/go/src/myapp/logs