# my global config
global:
  scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
- "instance_down.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
        - targets: ['localhost:9090']

  - job_name: 'gateway-api'
    scrape_interval: 5s
    static_configs:
      - targets: ['gateway-api:8080']
        labels:
          group: 'gateway-api'
  
  - job_name: 'user-srv'
    scrape_interval: 5s
    static_configs:
      - targets: ['user-srv:8088']
        labels:
          group: 'user-srv'

  - job_name: 'user-api'
    scrape_interval: 5s
    static_configs:
      - targets: ['user-api:8088']
        labels:
          group: 'user-api'